-- Configurar permissões padrão para roles usando valores corretos do enum
INSERT INTO role_permissions (employee_role, permission, granted) VALUES
-- Director - acesso total
('director', 'view_clients', true),
('director', 'create_clients', true),
('director', 'edit_clients', true),
('director', 'delete_clients', true),
('director', 'view_employees', true),
('director', 'create_employees', true),
('director', 'edit_employees', true),
('director', 'delete_employees', true),
('director', 'view_financial', true),
('director', 'create_financial', true),
('director', 'edit_financial', true),
('director', 'delete_financial', true),
('director', 'view_schedules', true),
('director', 'create_schedules', true),
('director', 'edit_schedules', true),
('director', 'delete_schedules', true),
('director', 'view_stock', true),
('director', 'create_stock', true),
('director', 'edit_stock', true),
('director', 'delete_stock', true),
('director', 'view_reports', true),
('director', 'create_reports', true),
('director', 'view_documents', true),
('director', 'create_documents', true),
('director', 'edit_documents', true),
('director', 'delete_documents', true),
('director', 'manage_roles', true),
('director', 'manage_permissions', true),
('director', 'view_audit_logs', true),
('director', 'system_admin', true),

-- Coordinator Madre
('coordinator_madre', 'view_clients', true),
('coordinator_madre', 'create_clients', true),
('coordinator_madre', 'edit_clients', true),
('coordinator_madre', 'view_schedules', true),
('coordinator_madre', 'create_schedules', true),
('coordinator_madre', 'edit_schedules', true),
('coordinator_madre', 'view_employees', true),
('coordinator_madre', 'edit_employees', true),
('coordinator_madre', 'view_stock', true),
('coordinator_madre', 'view_reports', true),
('coordinator_madre', 'create_reports', true),

-- Coordinator Floresta
('coordinator_floresta', 'view_clients', true),
('coordinator_floresta', 'create_clients', true),
('coordinator_floresta', 'edit_clients', true),
('coordinator_floresta', 'view_schedules', true),
('coordinator_floresta', 'create_schedules', true),
('coordinator_floresta', 'edit_schedules', true),
('coordinator_floresta', 'view_employees', true),
('coordinator_floresta', 'edit_employees', true),
('coordinator_floresta', 'view_stock', true),
('coordinator_floresta', 'view_reports', true),
('coordinator_floresta', 'create_reports', true),

-- Staff
('staff', 'view_clients', true),
('staff', 'create_clients', true),
('staff', 'edit_clients', true),
('staff', 'view_schedules', true),
('staff', 'create_schedules', true),
('staff', 'edit_schedules', true),
('staff', 'view_stock', true),
('staff', 'view_reports', true),

-- Financeiro
('financeiro', 'view_clients', true),
('financeiro', 'view_financial', true),
('financeiro', 'create_financial', true),
('financeiro', 'edit_financial', true),
('financeiro', 'view_reports', true),
('financeiro', 'create_reports', true),

-- Receptionist
('receptionist', 'view_clients', true),
('receptionist', 'create_clients', true),
('receptionist', 'edit_clients', true),
('receptionist', 'view_schedules', true),
('receptionist', 'create_schedules', true),
('receptionist', 'edit_schedules', true),

-- Psychologist, Speech Therapist, etc.
('psychologist', 'view_clients', true),
('psychologist', 'edit_clients', true),
('psychologist', 'view_schedules', true),
('psychologist', 'create_schedules', true),
('psychologist', 'edit_schedules', true),
('psychologist', 'view_reports', true),
('psychologist', 'create_reports', true),

('speech_therapist', 'view_clients', true),
('speech_therapist', 'edit_clients', true),
('speech_therapist', 'view_schedules', true),
('speech_therapist', 'create_schedules', true),
('speech_therapist', 'edit_schedules', true),
('speech_therapist', 'view_reports', true),
('speech_therapist', 'create_reports', true),

('nutritionist', 'view_clients', true),
('nutritionist', 'edit_clients', true),
('nutritionist', 'view_schedules', true),
('nutritionist', 'create_schedules', true),
('nutritionist', 'edit_schedules', true),
('nutritionist', 'view_reports', true),
('nutritionist', 'create_reports', true)

ON CONFLICT (employee_role, permission) DO UPDATE SET granted = EXCLUDED.granted;