// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vqphtzkdhfzdwbumexhe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZxcGh0emtkaGZ6ZHdidW1leGhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczNDIzODMsImV4cCI6MjA3MjkxODM4M30.Xa1UC2WmCaD9MMBvO_6kcXpsnTZRk5vpbxo_Gs2a2g4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});